### ISSUE TITLE
multipart module missing ?

### ISSUE THREAD

**Issue by weepy** [ciaranj/boardie#1]
Cannot find module 'multipart'

**Comment by ciaranj** [comment]
Fixed in 9cdb69392ae661772afff10ebed56579d42c5bca  Works with express 0.9.0 and node 0.1.92 my bad.
